# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-23 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageTransferWeb', '0002_diytask_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='diytask',
            name='diy_style_detail',
            field=models.IntegerField(default=1),
        ),
    ]
